
-- Creación de usuario en Oracle XE
CREATE USER PRACTICA_6 
IDENTIFIED BY PRACTICA_6
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION, RESOURCE TO PRACTICA_6;

